language: python
python:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
dist: bionic
os: linux
arch:
- arm64
jobs:
  fast_finish: true

before_install:
- pip install poetry
install:
- poetry install
script:
- black --check .
- coverage run --source=hebi -m pytest hebi/tests
# the samples from the README file
- >
  coverage run -a --source=hebi -m hebi eval examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=hebi -m hebi compile examples/smart_contracts/assert_sum.py > assert_sum.uplc
- >
  coverage run -a --source=hebi -m hebi eval_uplc examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=hebi -m hebi compile_pluto examples/smart_contracts/assert_sum.py
- >
  coverage run -a --source=hebi -m hebi build examples/smart_contracts/assert_sum.py
- >
  for i in $(find examples -type f -name "*.py" -not \( -name "broken*" -o -name "extract*" \)); do
    coverage run -a --source=hebi -m hebi compile "$i"
  done

after_success:
- coverage report
- coveralls
