[tool.poetry]
name = "hebi"
version = "0.1.1.0.11.0"
description = "A simple and fast pythonic programming language for Smart Contracts on Cardano"
authors = ["nielstron <n.muendler@web.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/opshin/hebi"
documentation = "https://hebi.opshin.dev/"
keywords = ["python", "language", "programming-language", "compiler", "validator", "smart-contracts", "cardano"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Compilers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
packages = [{include = "hebi"}]

[tool.poetry.dependencies]
python = ">=3.8, <3.12"
uplc = "0.6.0"
pluthon = "0.3.2"
pycardano = "0.7.2"
frozenlist = "1.3.3"

[tool.poetry.group.dev.dependencies]
hypothesis = "6.70.0"
parameterized = "0.8.1"
black = "22.12.0"
pre-commit = "^3.1.1"
coverage = "<7.0"
pytest = "^7.2.2"
coveralls = "^3.3.1"
poetry-bumpversion = "^0.3.0"

[tool.poetry.scripts]
hebi = "hebi.__main__:main"

[tool.poetry_bumpversion.file."hebi/__init__.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
