name: Python package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # If there isn't a release for this version, create a new one.
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: true
          prerelease: true
          skipIfReleaseExists: true
      # Build and publish the package to pypi.
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: "3.8"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          package_directory: "hebi"
          ignore_dev_requirements: "yes"
